name: publish

on:
  push:
    tags:
      - 'makecode-*' # Run workflow when any new semver-ish tag is pushed


jobs:
  filter-vtags:
    uses: ./.github/workflows/is-vtag.yml

  buildvtag:
    name: buildvtag
    # Only run this job if the push is a version tag
    needs: filter-vtags
    if: fromJSON(needs.filter-vtags.outputs.is_vtag || 'false') == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: npm install
        run: npm ci --workspaces

      - name: build packages
        run: npm run build --workspaces

      - name: run publish script
        run: node ./scripts/release.js publish
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN }}